x86, arm64 両方のdockerイメージをビルドするCIを設定
Idein/docker-cross-rpi pull request #11
Opened 2022-11-24 10:48 UTC by riku179

https://github.com/brain-hackers/docker-gen1-builder を参考に設定しました
必要があったので幾つくかMakefileも修正しています

2022-11-24 12:13 UTC, riku179 commented
この次にやることですが、
ClickUpのコメントにあった
> cross-rpiに依存しているbuilderコンテナをすべてbuildxでarm64向けにビルドし直してpushする

これがイマイチピンときていないのですが、具体的に何をどうすれば良いでしょうか

2022-11-24 12:26 UTC, tnishinaga requested changes
wipがなくなるようcommitを整理して再提出をお願いします。

2022-11-28 03:19 UTC, riku179 commented
@tnishinaga コミット整理しました

2022-11-28 04:00 UTC, tnishinaga approved these changes

2022-11-28 06:26 UTC, merged